apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
{{ if .Values.ingress.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backend-ingress
spec:
  entryPoints:
    - web
    {{ if .Values.ingress.secure }}
    - websecure
    {{ end }}
  routes:
    - match: Host(`{{.Values.ingress.hostname}}`) && PathPrefix(`/api`)
      kind: Rule
      priority: 11
      services:
        - name: backend-service
          port: 80
---
{{ end }}