name: HelmLinting

on:
  push:
    branches:
      - main
    paths:
      - "chart/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: "v3"

      - name: Lint Helm Chart
        run: |
          helm lint chart
